dist: trusty
sudo: required
notifications:
  email: false
language:
- cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - libsfml-dev
    - gcc-5
    - g++-5

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-5"; fi
- git clone --recursive https://github.com/Taktix-MMO/Taktix-Engine.git
- cd Taktix-Engine

before_script:
- sudo apt-get install -y xpra xserver-xorg-video-dummy
- export DISPLAY=:93
- export LIBGL_ALWAYS_SOFTWARE=1
- "xpra --xvfb=\"Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/Tests/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :93"
- sleep 3 
- LIBGL_ALWAYS_SOFTWARE=1 glxinfo
- glxinfo
- cat ${HOME}/.xpra/xorg.log
script:
- cd Build
- cmake -G 'Unix Makefiles' ..
- make -j
- "env DISPLAY=:93 ./Minimal_Application"

after_script:
- "xpra stop :93"
- "cat ~/.xpra/*"